export const LOADING = 'LOADING';

export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const FETCH_LOCKERS = 'FETCH_LOCKERS';
export const FETCH_LOCKER_GROUP = 'FETCH_LOCKER_GROUP';
export const FETCH_LOCKER_GROUP_ERROR = 'FETCH_LOCKER_GROUP_ERROR';
export const FETCH_LOCKERS_ERROR = 'FETCH_LOCKERS_ERROR';
export const LOCKER_RESERVATION = 'LOCKER_RESERVATION';

export const FETCH_ADDRESSES = 'FETCH_ADDRESSES';
export const FETCH_ADDRESSES_ERROR = 'FETCH_ADDRESSES_ERROR';