export const LOADING = 'LOADING';

export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const PROFILE = 'PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';
export const UPDATE_BASE_INFO = 'UPDATE_BASE_INFO';
export const UPDATE_BASE_INFO_ERROR = 'UPDATE_BASE_INFO_ERROR';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_EMAIL_ERROR = 'UPDATE_EMAIL_ERROR';
export const SEND_CONFIRM_CODE = 'SEND_CONFIRM_CODE';
export const SEND_CONFIRM_CODE_ERROR = 'SEND_CONFIRM_CODE_ERROR';

export const FETCH_LOCKERS = 'FETCH_LOCKERS';
export const FETCH_LOCKER_GROUP = 'FETCH_LOCKER_GROUP';
export const FETCH_LOCKER_GROUP_ERROR = 'FETCH_LOCKER_GROUP_ERROR';
export const FETCH_LOCKERS_ERROR = 'FETCH_LOCKERS_ERROR';
export const FETCH_LOCKER = 'FETCH_LOCKER';
export const FETCH_LOCKER_ERROR = 'FETCH_LOCKER_ERROR';

export const LOCKER_RESERVATION = 'LOCKER_RESERVATION';
export const CREATE_RESERVATION = 'CREATE_RESERVATION';
export const CREATE_RESERVATION_ERROR = 'CREATE_RESERVATION_ERROR';
export const UPDATE_RESERVATION_STATUS = 'UPDATE_RESERVATION_STATUS';
export const UPDATE_RESERVATION_STATUS_ERROR = 'UPDATE_RESERVATION_STATUS_ERROR';
export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS';
export const FETCH_RESERVATIONS_ERROR = 'FETCH_RESERVATIONS_ERROR';
export const CLEAN_FETCH_RESERVATIONS = 'CLEAN_FETCH_RESERVATIONS';
export const FETCH_RESERVATION = 'FETCH_RESERVATION';
export const FETCH_RESERVATION_ERROR = 'FETCH_RESERVATION_ERROR';
export const FINISH_RESERVATION = 'FINISH_RESERVATION';
export const FINISH_RESERVATION_ERROR = 'FINISH_RESERVATION_ERROR';

export const FETCH_ADDRESSES = 'FETCH_ADDRESSES';
export const FETCH_ADDRESSES_ERROR = 'FETCH_ADDRESSES_ERROR';

export const PAYMENT = 'PAYMENT';
export const PAYMENT_ERROR = 'PAYMENT_ERROR';